# Generated by Django 3.0.8 on 2021-03-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='分类名')),
                ('category_rank', models.IntegerField(default=1, verbose_name='优先级(越大越优先)')),
            ],
            options={
                'verbose_name': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('product_description', models.TextField(verbose_name='商品介绍')),
                ('product_price', models.FloatField(default=0.0, verbose_name='商品价格')),
                ('product_amount', models.IntegerField(default=9999, verbose_name='商品数量')),
                ('product_status', models.BooleanField(default=True, verbose_name='商品出售中')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='商品创建时间')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
            ],
            options={
                'verbose_name': '商品管理',
            },
        ),
    ]
